<?php

namespace Database\Seeders;

use App\Models\ServiceTemplate;
use App\Models\Specialization;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ServiceTemplatePlumberSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $specializationId = Specialization::whereCode(Specialization::PLUMBER)->get()->first()->id;
        $parentId = null;

        // основные направления по сантехнике
        ServiceTemplate::insert([
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                //'name' => 'Сантехник в {:prepositional}',
                //'name' => 'Сантехник {:name}',
                'name' => 'Услуги сантехника в {:prepositional}',
                'catalog_name' => 'Услуги сантехника',
                'code' => str_slug('Услуги сантехника'),
                'h1' => 'Частный сантехник в {:prepositional}',
                //'title' => 'Услуги сантехника в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'title' => 'Срочный вызов сантехника в {:prepositional} по выгодной цене',
                //'title' => 'Услуги сантехника в {:prepositional}, срочный вызов на дом мастера',
                'description' => 'Услуги сантехника в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'услуги сантехника, сантехник на дом, вызов сантехника, сантехник, профессиональные
                               сантехники, {:name}',
                'default_template' => 'templates.services.plumber.plumbing_services',
                'main_service' => true,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 1
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Установка сантехники в {:prepositional}',
                'catalog_name' => 'Установка сантехники',
                'code' => str_slug('Установка сантехники'),
                'h1' => 'Установка сантехники в {:prepositional}',
                'title' => 'Установка сантехники в {:prepositional}',
                'description' => 'Установка сантехники в {:prepositional}',
                'keywords' => 'сантехника, установка, {:name}',
                'default_template' => 'templates.services.plumber.ustanovka_santexniki',
                'main_service' => false,
                'on_city_list' => true,
                'section' => true,
                'default_price' => '700',
                'sort' => 2
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Замена сантехники в {:prepositional}',
                'catalog_name' => 'Замена сантехники',
                'code' => str_slug('Замена сантехники'),
                'h1' => 'Замена сантехники в {:prepositional}',
                'title' => 'Замена сантехники в {:prepositional}',
                'description' => 'Замена сантехники в {:prepositional}',
                'keywords' => 'сантехника, замена, {:name}',
                'default_template' => 'templates.services.plumber.zamena_santexniki',
                'main_service' => false,
                'on_city_list' => true,
                'section' => true,
                'default_price' => '700',
                'sort' => 3
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Ремонт сантехники в {:prepositional}',
                'catalog_name' => 'Ремонт сантехники',
                'code' => str_slug('Ремонт сантехники'),
                'h1' => 'Ремонт сантехники в {:prepositional}',
                'title' => 'Ремонт сантехники в {:prepositional}',
                'keywords' => 'сантехника, ремонт, {:name}',
                'description' => 'Ремонт сантехники в {:prepositional}',
                'default_template' => 'templates.services.plumber.remont_santexniki',
                'main_service' => false,
                'on_city_list' => true,
                'section' => true,
                'default_price' => '700',
                'sort' => 4
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Устранение засоров в {:prepositional}',
                'catalog_name' => 'Устранение засоров',
                'code' => str_slug('Устранение засоров'),
                'h1' => 'Устранение засоров в {:prepositional}',
                'title' => 'Устранение засоров в {:prepositional}',
                'keywords' => 'засор, устранение, {:name}',
                'description' => 'Устранение засоров в {:prepositional}',
                'default_template' => 'templates.services.plumber.removing_blockages',
                'main_service' => false,
                'on_city_list' => true,
                'section' => true,
                'default_price' => '700',
                'sort' => 5
            ]
        ]);

        $parentId = ServiceTemplate::whereCode(str_slug('Установка сантехники'))->get()->first()->id;

        ServiceTemplate::insert([
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Установка смесителя в {:prepositional}',
                'catalog_name' => 'Установка смесителя',
                'code' => str_slug('Установка смесителя'),
                'h1' => 'Установка смесителя в {:prepositional}',
                'title' => 'Установка смесителя в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Установка смесителя в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, установка, смеситель, {:name}',
                'default_template' => 'templates.services.plumber.installation.1-mixer_installation',
                'main_service' => false,
                'on_city_list' => true,
                'section' => false,
                'default_price' => '700',
                'sort' => 6
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Установка унитаза в {:prepositional}',
                'catalog_name' => 'Установка унитаза',
                'code' => str_slug('Установка унитаза'),
                'h1' => 'Установка унитаза в {:prepositional}',
                'title' => 'Установка унитаза в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Установка унитаза в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, установка, унитаз, {:name}',
                'default_template' => 'templates.services.plumber.installation.2-toilet_installation',
                'main_service' => false,
                'on_city_list' => true,
                'section' => false,
                'default_price' => '700',
                'sort' => 7
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Установка ванны в {:prepositional}',
                'catalog_name' => 'Установка ванны',
                'code' => str_slug('Установка ванны'),
                'h1' => 'Установка ванны в {:prepositional}',
                'title' => 'Установка ванны в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Установка ванны в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, установка, ванна, {:name}',
                'default_template' => 'templates.services.plumber.installation.3-bath_installation',
                'main_service' => false,
                'on_city_list' => true,
                'section' => false,
                'default_price' => '700',
                'sort' => 8
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Установка раковины в {:prepositional}',
                'catalog_name' => 'Установка раковины',
                'code' => str_slug('Установка раковины'),
                'h1' => 'Установка раковины в {:prepositional}',
                'title' => 'Установка раковины в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Установка раковины в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, установка, раковина, {:name}',
                'default_template' => 'templates.services.plumber.installation.4-sink_installation',
                'main_service' => false,
                'on_city_list' => true,
                'section' => false,
                'default_price' => '700',
                'sort' => 9
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Установка радиатора отопления в {:prepositional}',
                'catalog_name' => 'Установка радиатора отопления',
                'code' => str_slug('Установка радиатора отопления'),
                'h1' => 'Установка радиатора отопления в {:prepositional}',
                'title' => 'Установка радиатора отопления в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Установка радиатора отопления в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, установка, радиатор отопления, {:name}',
                'default_template' => 'templates.services.plumber.installation.5-heating_radiators_installation',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 10
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Установка душевой кабины в {:prepositional}',
                'catalog_name' => 'Установка душевой кабины',
                'code' => str_slug('Установка душевой кабины'),
                'h1' => 'Установка душевой кабины в {:prepositional}',
                'title' => 'Установка душевой кабины в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Установка душевой кабины в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, установка, душевая кабина, {:name}',
                'default_template' => 'templates.services.plumber.installation.6-shower_cabin_installation',
                'main_service' => false,
                'on_city_list' => true,
                'section' => false,
                'default_price' => '700',
                'sort' => 11
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Установка водонагревателя в {:prepositional}',
                'catalog_name' => 'Установка водонагревателя',
                'code' => str_slug('Установка водонагревателя'),
                'h1' => 'Установка водонагревателя в {:prepositional}',
                'title' => 'Установка водонагревателя в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Установка водонагревателя в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, установка, водонагреватель, {:name}',
                'default_template' => 'templates.services.plumber.installation.7-water_heater_installation',
                'main_service' => false,
                'on_city_list' => true,
                'section' => false,
                'default_price' => '700',
                'sort' => 12
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Установка полотенцесушителя в {:prepositional}',
                'catalog_name' => 'Установка полотенцесушителя',
                'code' => str_slug('Установка полотенцесушителя'),
                'h1' => 'Установка полотенцесушителя в {:prepositional}',
                'title' => 'Установка полотенцесушителя в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Установка полотенцесушителя в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, установка, полотенцесушитель, {:name}',
                'default_template' => 'templates.services.plumber.installation.8-heated_towel_rail_installation',
                'main_service' => false,
                'on_city_list' => true,
                'section' => false,
                'default_price' => '700',
                'sort' => 13
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Установка фильтра для воды в {:prepositional}',
                'catalog_name' => 'Установка фильтра для воды',
                'code' => str_slug('Установка фильтра для воды'),
                'h1' => 'Установка фильтра для воды в {:prepositional}',
                'title' => 'Установка фильтра для воды в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Установка фильтра для воды в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, установка, фильтр для воды, {:name}',
                'default_template' => 'templates.services.plumber.installation.9-water_filters_installation',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 14
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Установка шаровых кранов в {:prepositional}',
                'catalog_name' => 'Установка шаровых кранов',
                'code' => str_slug('Установка шаровых кранов'),
                'h1' => 'Установка шаровых кранов в {:prepositional}',
                'title' => 'Установка шаровых кранов в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Установка шаровых кранов в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, установка, шаровый кран, {:name}',
                'default_template' => 'templates.services.plumber.installation.10-ball_valves_installation',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 16
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Монтаж труб водоснабжения в {:prepositional}',
                'catalog_name' => 'Монтаж труб водоснабжения',
                'code' => str_slug('Монтаж труб водоснабжения'),
                'h1' => 'Монтаж труб водоснабжения в {:prepositional}',
                'title' => 'Монтаж труб водоснабжения в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Установка труб водоснабжения в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, установка, трубы водоснабжения, {:name}',
                'default_template' => 'templates.services.plumber.installation.11-water_pipes_installation',
                'main_service' => false,
                'on_city_list' => true,
                'section' => false,
                'default_price' => '700',
                'sort' => 17
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Монтаж канализационных труб в {:prepositional}',
                'catalog_name' => 'Монтаж канализационных труб',
                'code' => str_slug('Монтаж канализационных труб'),
                'h1' => 'Монтаж канализационных труб в {:prepositional}',
                'title' => 'Монтаж канализационных труб в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Монтаж канализационных труб в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, монтаж, канализационные трубы, {:name}',
                'default_template' => 'templates.services.plumber.installation.12-sewer_pipes_installation',
                'main_service' => false,
                'on_city_list' => true,
                'section' => false,
                'default_price' => '700',
                'sort' => 18
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Установка мойки в {:prepositional}',
                'catalog_name' => 'Установка мойки',
                'code' => str_slug('Установка мойки'),
                'h1' => 'Установка мойки в {:prepositional}',
                'title' => 'Установка мойки в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Установка мойки в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, установка, мойка, {:name}',
                'default_template' => 'templates.services.plumber.installation.13-washing_installation',
                'main_service' => false,
                'on_city_list' => true,
                'section' => false,
                'default_price' => '700',
                'sort' => 19
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Установка биде в {:prepositional}',
                'catalog_name' => 'Установка биде',
                'code' => str_slug('Установка биде'),
                'h1' => 'Установка биде в {:prepositional}',
                'title' => 'Установка биде в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Установка биде в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, установка, биде, {:name}',
                'default_template' => 'templates.services.plumber.installation.14-bidet_installation',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 20
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Установка инсталляции унитаза в {:prepositional}',
                'catalog_name' => 'Установка инсталляции унитаза',
                'code' => str_slug('Установка инсталляции унитаза в'),
                'h1' => 'Установка инсталляции унитаза в {:prepositional}',
                'title' => 'Установка инсталляции унитаза в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Установка инсталляции унитаза в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, установка, инсталляция, {:name}',
                'default_template' => 'templates.services.plumber.installation.15-installation_installation',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 21
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Установка джакузи в {:prepositional}',
                'catalog_name' => 'Установка джакузи',
                'code' => str_slug('Установка джакузи'),
                'h1' => 'Установка джакузи в {:prepositional}',
                'title' => 'Установка джакузи в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Установка джакузи в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, установка, джакузи, {:name}',
                'default_template' => 'templates.services.plumber.installation.16-jacuzzi_installation',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 22
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Установка стиральной машины в {:prepositional}',
                'catalog_name' => 'Установка стиральной машины',
                'code' => str_slug('Установка стиральной машины'),
                'h1' => 'Установка стиральной машины в {:prepositional}',
                'title' => 'Установка стиральной машины в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Установка стиральной машины в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, установка, стиральная машина, {:name}',
                'default_template' => 'templates.services.plumber.installation.17-washing_machine_installation',
                'main_service' => false,
                'on_city_list' => true,
                'section' => false,
                'default_price' => '700',
                'sort' => 23
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Установка посудомоечной машины в {:prepositional}',
                'catalog_name' => 'Установка посудомоечной машины',
                'code' => str_slug('Установка посудомоечной машины'),
                'h1' => 'Установка посудомоечной машины в {:prepositional}',
                'title' => 'Установка посудомоечной машины в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Установка посудомоечной машины в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, установка, посудомоечная машина, {:name}',
                'default_template' => 'templates.services.plumber.installation.18-dishwasher_installation',
                'main_service' => false,
                'on_city_list' => true,
                'section' => false,
                'default_price' => '700',
                'sort' => 24
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Установка мойдодыра в {:prepositional}',
                'catalog_name' => 'Установка мойдодыра',
                'code' => str_slug('Установка мойдодыра'),
                'h1' => 'Установка мойдодыра в {:prepositional}',
                'title' => 'Установка мойдодыра в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Установка мойдодыра в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, установка, мойдодыр, {:name}',
                'default_template' => 'templates.services.plumber.installation.19-moidodyr_installation',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 25
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Установка душевого уголка в {:prepositional}',
                'catalog_name' => 'Установка душевого уголка',
                'code' => str_slug('Установка душевого уголка'),
                'h1' => 'Установка душевого уголка в {:prepositional}',
                'title' => 'Установка душевого уголка в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Установка душевого уголка в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, установка, душевой уголок, {:name}',
                'default_template' => 'templates.services.plumber.installation.20-shower_enclosure_installation',
                'main_service' => false,
                'on_city_list' => true,
                'section' => false,
                'default_price' => '700',
                'sort' => 26
            ]
        ]);

        $parentId = ServiceTemplate::whereCode(str_slug('Замена сантехники'))->get()->first()->id;

        ServiceTemplate::insert([
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Замена смесителя в {:prepositional}',
                'catalog_name' => 'Замена смесителя',
                'code' => str_slug('Замена смесителя'),
                'h1' => 'Замена смесителя в {:prepositional}',
                'title' => 'Замена смесителя в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Замена смесителя в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, замена, смеситель, {:name}',
                'default_template' => 'templates.services.plumber.replacement.1-mixer_replacement',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 27
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Замена унитаза в {:prepositional}',
                'catalog_name' => 'Замена унитаза',
                'code' => str_slug('Замена унитаза'),
                'h1' => 'Замена унитаза в {:prepositional}',
                'title' => 'Замена унитаза в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Замена унитаза в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, замена, унитаз, {:name}',
                'default_template' => 'templates.services.plumber.replacement.2-toilet_replacement',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 28
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Замена ванны в {:prepositional}',
                'catalog_name' => 'Замена ванны',
                'code' => str_slug('Замена ванны'),
                'h1' => 'Замена ванны в {:prepositional}',
                'title' => 'Замена ванны в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Замена ванны в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, замена, ванна, {:name}',
                'default_template' => 'templates.services.plumber.replacement.3-bath_replacement',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 29
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Замена раковины в {:prepositional}',
                'catalog_name' => 'Замена раковины',
                'code' => str_slug('Замена раковины'),
                'h1' => 'Замена раковины в {:prepositional}',
                'title' => 'Замена раковины в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Замена раковины в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, замена, раковина, {:name}',
                'default_template' => 'templates.services.plumber.replacement.4-sink_replacement',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 30
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Замена радиатора отопления в {:prepositional}',
                'catalog_name' => 'Замена радиатора отопления',
                'code' => str_slug('Замена радиатора отопления'),
                'h1' => 'Замена радиатора отопления в {:prepositional}',
                'title' => 'Замена радиатора отопления в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Замена радиатора отопления в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, замена, радиатор отопления, {:name}',
                'default_template' => 'templates.services.plumber.replacement.5-heating_radiators_replacement',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 31
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Замена душевой кабины в {:prepositional}',
                'catalog_name' => 'Замена душевой кабины',
                'code' => str_slug('Замена душевой кабины'),
                'h1' => 'Замена душевой кабины в {:prepositional}',
                'title' => 'Замена душевой кабины в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Замена душевой кабины в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, замена, душевая кабина, {:name}',
                'default_template' => 'templates.services.plumber.replacement.6-shower_cabin_replacement',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 32
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Замена водонагревателя в {:prepositional}',
                'catalog_name' => 'Замена водонагревателя',
                'code' => str_slug('Замена водонагревателя'),
                'h1' => 'Замена водонагревателя в {:prepositional}',
                'title' => 'Замена водонагревателя в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Замена водонагревателя в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, замена, водонагреватель, {:name}',
                'default_template' => 'templates.services.plumber.replacement.7-water_heater_replacement',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 33
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Замена полотенцесушителя в {:prepositional}',
                'catalog_name' => 'Замена полотенцесушителя',
                'code' => str_slug('Замена полотенцесушителя'),
                'h1' => 'Замена полотенцесушителя в {:prepositional}',
                'title' => 'Замена полотенцесушителя в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Замена полотенцесушителя в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, замена, полотенцесушитель, {:name}',
                'default_template' => 'templates.services.plumber.replacement.8-heated_towel_rail_replacement',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 34
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Замена фильтра для воды в {:prepositional}',
                'catalog_name' => 'Замена фильтра для воды',
                'code' => str_slug('Замена фильтра для воды'),
                'h1' => 'Замена фильтра для воды в {:prepositional}',
                'title' => 'Замена фильтра для воды в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Замена фильтра для воды в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, замена, фильтр для воды, {:name}',
                'default_template' => 'templates.services.plumber.replacement.9-water_filters_replacement',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 35
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Замена шаровых кранов в {:prepositional}',
                'catalog_name' => 'Замена шаровых кранов',
                'code' => str_slug('Замена шаровых кранов'),
                'h1' => 'Замена шаровых кранов в {:prepositional}',
                'title' => 'Замена шаровых кранов в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Замена шаровых кранов в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, замена, шаровый кран, {:name}',
                'default_template' => 'templates.services.plumber.replacement.10-ball_valves_replacement',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 36
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Замена труб водоснабжения в {:prepositional}',
                'catalog_name' => 'Замена труб водоснабжения',
                'code' => str_slug('Замена труб водоснабжения'),
                'h1' => 'Замена труб водоснабжения в {:prepositional}',
                'title' => 'Замена труб водоснабжения в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Замена труб водоснабжения в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, замена, трубы водоснабжения, {:name}',
                'default_template' => 'templates.services.plumber.replacement.11-water_pipes_replacement',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 37
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Замена канализационных труб в {:prepositional}',
                'catalog_name' => 'Замена канализационных труб',
                'code' => str_slug('Замена канализационных труб'),
                'h1' => 'Замена канализационных труб в {:prepositional}',
                'title' => 'Замена канализационных труб в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Замена канализационных труб в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, замена, канализационные трубы, {:name}',
                'default_template' => 'templates.services.plumber.replacement.12-sewer_pipes_replacement',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 38
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Замена мойки в {:prepositional}',
                'catalog_name' => 'Замена мойки',
                'code' => str_slug('Замена мойки'),
                'h1' => 'Замена мойки в {:prepositional}',
                'title' => 'Замена мойки в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Замена мойки в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, замена, мойка, {:name}',
                'default_template' => 'templates.services.plumber.replacement.13-washing_replacement',
                'main_service' => false,
                'on_city_list' => true,
                'section' => false,
                'default_price' => '700',
                'sort' => 39
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Замена бачка унитаза в {:prepositional}',
                'catalog_name' => 'Замена бачка унитаза',
                'code' => str_slug('Замена бачка унитаза'),
                'h1' => 'Замена бачка унитаза в {:prepositional}',
                'title' => 'Замена бачка унитаза в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Замена бачка унитаза в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, замена, бачок унитаза, {:name}',
                'default_template' => 'templates.services.plumber.replacement.14-toilet_cistern_replacement',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 40
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Замена сифона в {:prepositional}',
                'catalog_name' => 'Замена сифона',
                'code' => str_slug('Замена сифона'),
                'h1' => 'Замена сифона в {:prepositional}',
                'title' => 'Замена сифона в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Замена сифона в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, замена, сифон, {:name}',
                'default_template' => 'templates.services.plumber.replacement.15-siphon_replacement',
                'main_service' => false,
                'on_city_list' => true,
                'section' => false,
                'default_price' => '700',
                'sort' => 41
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Замена слива в {:prepositional}',
                'catalog_name' => 'Замена слива',
                'code' => str_slug('Замена слива'),
                'h1' => 'Замена слива в {:prepositional}',
                'title' => 'Замена слива в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Замена слива в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, замена, слив, {:name}',
                'default_template' => 'templates.services.plumber.replacement.16-drain_replacement',
                'main_service' => false,
                'on_city_list' => true,
                'section' => false,
                'default_price' => '700',
                'sort' => 42
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Замена крана-буксы в {:prepositional}',
                'catalog_name' => 'Замена крана-буксы',
                'code' => str_slug('Замена крана-буксы'),
                'h1' => 'Замена крана-буксы в {:prepositional}',
                'title' => 'Замена крана-буксы в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Замена крана-буксы в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, замена, кран-букса, {:name}',
                'default_template' => 'templates.services.plumber.replacement.17-crane_replacement',
                'main_service' => false,
                'on_city_list' => true,
                'section' => false,
                'default_price' => '700',
                'sort' => 43
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Замена картриджа в {:prepositional}',
                'catalog_name' => 'Замена картриджа',
                'code' => str_slug('Замена картриджа'),
                'h1' => 'Замена картриджа в {:prepositional}',
                'title' => 'Замена картриджа в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Замена картриджа в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, замена, картридж, {:name}',
                'default_template' => 'templates.services.plumber.replacement.18-cartridge_replacement',
                'main_service' => false,
                'on_city_list' => true,
                'section' => false,
                'default_price' => '700',
                'sort' => 44
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Замена гофры унитаза в {:prepositional}',
                'catalog_name' => 'Замена гофры унитаза',
                'code' => str_slug('Замена гофры унитаза'),
                'h1' => 'Замена гофры унитаза в {:prepositional}',
                'title' => 'Замена гофры унитаза в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Замена гофры унитаза в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, замена, гофра унитаза, {:name}',
                'default_template' => 'templates.services.plumber.replacement.19-toilet_corrugation_replacement',
                'main_service' => false,
                'on_city_list' => true,
                'section' => false,
                'default_price' => '700',
                'sort' => 45
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Замена арматуры бачка унитаза в {:prepositional}',
                'catalog_name' => 'Замена арматуры бачка унитаза',
                'code' => str_slug('Замена арматуры бачка унитаза'),
                'h1' => 'Замена арматуры бачка унитаза в {:prepositional}',
                'title' => 'Замена арматуры бачка унитаза в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Замена арматуры бачка унитаза в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, замена, замена арматуры бачка унитаза, {:name}',
                'default_template' => 'templates.services.plumber.replacement.20-toilet_cistern_fittings',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 46
            ]
        ]);

        $parentId = ServiceTemplate::whereCode(str_slug('Ремонт сантехники'))->get()->first()->id;

        ServiceTemplate::insert([
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Ремонт смесителя в {:prepositional}',
                'catalog_name' => 'Ремонт смесителя',
                'code' => str_slug('Ремонт смесителя'),
                'h1' => 'Ремонт смесителя в {:prepositional}',
                'title' => 'Ремонт смесителя в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Ремонт смесителя в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, ремонт, смеситель, {:name}',
                'default_template' => 'templates.services.plumber.repair.1-mixer_repair',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 47
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Ремонт унитаза в {:prepositional}',
                'catalog_name' => 'Ремонт унитаза',
                'code' => str_slug('Ремонт унитаза'),
                'h1' => 'Ремонт унитаза в {:prepositional}',
                'title' => 'Ремонт унитаза в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Ремонт унитаза в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, ремонт, унитаз, {:name}',
                'default_template' => 'templates.services.plumber.repair.2-toilet_repair',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 48
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Ремонт ванны унитаза в {:prepositional}',
                'catalog_name' => 'Ремонт ванны',
                'code' => str_slug('Ремонт ванны'),
                'h1' => 'Ремонт ванны в {:prepositional}',
                'title' => 'Ремонт ванны в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Ремонт ванны в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, ремонт, ванна, {:name}',
                'default_template' => 'templates.services.plumber.repair.3-bath_repair',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 49
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Ремонт раковины в {:prepositional}',
                'catalog_name' => 'Ремонт раковины',
                'code' => str_slug('Ремонт раковины'),
                'h1' => 'Ремонт раковины в {:prepositional}',
                'title' => 'Ремонт раковины в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Ремонт раковины в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, ремонт, раковина, {:name}',
                'default_template' => 'templates.services.plumber.repair.4-sink_repair',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 50
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Ремонт радиатора отопления в {:prepositional}',
                'catalog_name' => 'Ремонт радиатора отопления',
                'code' => str_slug('Ремонт радиатора отопления'),
                'h1' => 'Ремонт радиатора отопления в {:prepositional}',
                'title' => 'Ремонт радиатора отопления в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Ремонт радиатора отопления в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, ремонт, радиатор отопления, {:name}',
                'default_template' => 'templates.services.plumber.repair.5-heating_radiators_repair',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 51
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Ремонт душевой кабины в {:prepositional}',
                'catalog_name' => 'Ремонт душевой кабины',
                'code' => str_slug('Ремонт душевой кабины'),
                'h1' => 'Ремонт душевой кабины в {:prepositional}',
                'title' => 'Ремонт душевой кабины в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Ремонт душевой кабины в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, ремонт, душевая кабина, {:name}',
                'default_template' => 'templates.services.plumber.repair.6-shower_cabin_repair',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 52
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Ремонт водонагревателя в {:prepositional}',
                'catalog_name' => 'Ремонт водонагревателя',
                'code' => str_slug('Ремонт водонагревателя'),
                'h1' => 'Ремонт водонагревателя в {:prepositional}',
                'title' => 'Ремонт водонагревателя в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Ремонт водонагревателя в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, ремонт, водонагреватель, {:name}',
                'default_template' => 'templates.services.plumber.repair.7-water_heater_repair',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 53
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Ремонт полотенцесушителя в {:prepositional}',
                'catalog_name' => 'Ремонт полотенцесушителя',
                'code' => str_slug('Ремонт полотенцесушителя'),
                'h1' => 'Ремонт полотенцесушителя в {:prepositional}',
                'title' => 'Ремонт полотенцесушителя в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Ремонт полотенцесушителя в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, ремонт, полотенцесушитель, {:name}',
                'default_template' => 'templates.services.plumber.repair.8-heated_towel_rail_repair',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 54
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Ремонт фильтра для воды в {:prepositional}',
                'catalog_name' => 'Ремонт фильтра для воды',
                'code' => str_slug('Ремонт фильтра для воды'),
                'h1' => 'Ремонт фильтра для воды в {:prepositional}',
                'title' => 'Ремонт фильтра для воды в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Ремонт фильтра для воды в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, ремонт, фильтр для воды, {:name}',
                'default_template' => 'templates.services.plumber.repair.9-water_filters_repair',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 55
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Ремонт шаровых кранов в {:prepositional}',
                'catalog_name' => 'Ремонт шаровых кранов',
                'code' => str_slug('Ремонт шаровых кранов'),
                'h1' => 'Ремонт шаровых кранов в {:prepositional}',
                'title' => 'Ремонт шаровых кранов в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Ремонт шаровых кранов в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, ремонт, шаровый кран, {:name}',
                'default_template' => 'templates.services.plumber.repair.10-ball_valves_repair',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 56
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Ремонт труб водоснабжения в {:prepositional}',
                'catalog_name' => 'Ремонт труб водоснабжения',
                'code' => str_slug('Ремонт труб водоснабжения'),
                'h1' => 'Ремонт труб водоснабжения в {:prepositional}',
                'title' => 'Ремонт труб водоснабжения в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Ремонт труб водоснабжения в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, ремонт, труба, водоснабжение, {:name}',
                'default_template' => 'templates.services.plumber.repair.11-water_pipes_repair',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 57
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Ремонт канализационных труб в {:prepositional}',
                'catalog_name' => 'Ремонт канализационных труб',
                'code' => str_slug('Ремонт канализационных труб'),
                'h1' => 'Ремонт канализационных труб в {:prepositional}',
                'title' => 'Ремонт канализационных труб в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Ремонт канализационных труб в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, ремонт, канализационные трубы, {:name}',
                'default_template' => 'templates.services.plumber.repair.12-sewer_pipes_repair',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 58
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Ремонт биде в {:prepositional}',
                'catalog_name' => 'Ремонт биде',
                'code' => str_slug('Ремонт биде'),
                'h1' => 'Ремонт биде в {:prepositional}',
                'title' => 'Ремонт биде в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Ремонт биде в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, ремонт, биде, {:name}',
                'default_template' => 'templates.services.plumber.repair.13-bidet_repair',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 59
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Ремонт инсталляции унитаза в {:prepositional}',
                'catalog_name' => 'Ремонт инсталляции унитаза',
                'code' => str_slug('Ремонт инсталляции унитаза'),
                'h1' => 'Ремонт инсталляции унитаза в {:prepositional}',
                'title' => 'Ремонт инсталляции унитаза в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Ремонт инсталляции унитаза в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, ремонт, инсталляция, {:name}',
                'default_template' => 'templates.services.plumber.repair.14-installation_repair',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 60
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Ремонт джакузи в {:prepositional}',
                'catalog_name' => 'Ремонт джакузи',
                'code' => str_slug('Ремонт джакузи'),
                'h1' => 'Ремонт джакузи в {:prepositional}',
                'title' => 'Ремонт джакузи в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Ремонт джакузи в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, ремонт, джакузи, {:name}',
                'default_template' => 'templates.services.plumber.repair.15-jacuzzi_repair',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 61
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Ремонт труб отопления в {:prepositional}',
                'catalog_name' => 'Ремонт труб отопления',
                'code' => str_slug('Ремонт труб отопления'),
                'h1' => 'Ремонт труб отопления в {:prepositional}',
                'title' => 'Ремонт труб отопления в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Ремонт труб отопления в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, ремонт, труба отопления, {:name}',
                'default_template' => 'templates.services.plumber.repair.16-pipe_repair',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 62
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Герметизация швов в ванной в {:prepositional}',
                'catalog_name' => 'Герметизация швов в ванной',
                'code' => str_slug('Герметизация швов в ванной'),
                'h1' => 'Герметизация швов в ванной в {:prepositional}',
                'title' => 'Герметизация швов в ванной в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Герметизация швов в ванной в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, ремонт, швы, ванна, герметизация, {:name}',
                'default_template' => 'templates.services.plumber.repair.17-sealing_joints_bathroom',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 63
            ]
        ]);

        $parentId = ServiceTemplate::whereCode(str_slug('Устранение засоров'))->get()->first()->id;

        ServiceTemplate::insert([
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Устранение засоров канализации в {:prepositional}',
                'catalog_name' => 'Устранение засоров канализации',
                'code' => str_slug('Устранение засоров канализации'),
                'h1' => 'Устранение засоров канализации в {:prepositional}',
                'title' => 'Устранение засоров канализации в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Устранение засоров канализации в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, засор канализации, {:name}',
                'default_template' => 'templates.services.plumber.removing_blockages.1-sewer_blockages_clearing',
                'main_service' => false,
                'on_city_list' => true,
                'section' => false,
                'default_price' => '700',
                'sort' => 60
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Устранение засора в ванной в {:prepositional}',
                'catalog_name' => 'Устранение засора в ванной',
                'code' => str_slug('Устранение засора в ванной'),
                'h1' => 'Устранение засора в ванной в {:prepositional}',
                'title' => 'Устранение засора в ванной в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Устранение засора в ванной в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, засор ванны, {:name}',
                'default_template' => 'templates.services.plumber.removing_blockages.2-clog_bathroom_clearing',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 61
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Устранение засора в душевой кабине в {:prepositional}',
                'catalog_name' => 'Устранение засора в душевой кабине',
                'code' => str_slug('Устранение засора в душевой кабине'),
                'h1' => 'Устранение засора в душевой кабине в {:prepositional}',
                'title' => 'Устранение засора в душевой кабине в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Устранение засора в душевой кабине в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, засор душевой кабины, {:name}',
                'default_template' => 'templates.services.plumber.removing_blockages.3-shower_cabin_clearing',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 62
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Устранение засора в раковине в {:prepositional}',
                'catalog_name' => 'Устранение засора в раковине',
                'code' => str_slug('Устранение засора в раковине'),
                'h1' => 'Устранение засора в раковине в {:prepositional}',
                'title' => 'Устранение засора в раковине в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Устранение засора в раковине в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, засор раковины, {:name}',
                'default_template' => 'templates.services.plumber.removing_blockages.4-sink_clearing',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 63
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Устранение засора на кухне в {:prepositional}',
                'catalog_name' => 'Устранение засора на кухне',
                'code' => str_slug('Устранение засора на кухне'),
                'h1' => 'Устранение засора на кухне в {:prepositional}',
                'title' => 'Устранение засора на кухне в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Устранение засора на кухне в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, засор на кухне, {:name}',
                'default_template' => 'templates.services.plumber.removing_blockages.5-kitchen_clearing',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 64
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Устранение засора унитаза в {:prepositional}',
                'catalog_name' => 'Устранение засора унитаза',
                'code' => str_slug('Устранение засора унитаза'),
                'h1' => 'Устранение засора унитаза в {:prepositional}',
                'title' => 'Устранение засора унитаза в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Устранение засора унитаза в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, засор унитаза, {:name}',
                'default_template' => 'templates.services.plumber.removing_blockages.6-toilet_clearing',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 65
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Устранение засоров гидродинамическим способом в {:prepositional}',
                'catalog_name' => 'Устранение засоров гидродинамическим способом',
                'code' => str_slug('Устранение засоров гидродинамическим способом'),
                'h1' => 'Устранение засоров гидродинамическим способом в {:prepositional}',
                'title' => 'Устранение засоров гидродинамическим способом в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Устранение засоров гидродинамическим способом в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, засор, унитаза, гидродинамический способ, {:name}',
                'default_template' => 'templates.services.plumber.removing_blockages.7-hydrodynamic_method_clearing',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 66
            ],
            [
                'specialization_id' => $specializationId,
                'parent_id' => $parentId,
                'name' => 'Устранение засоров механическим способом в {:prepositional}',
                'catalog_name' => 'Устранение засоров механическим способом',
                'code' => str_slug('Устранение засоров механическим способом'),
                'h1' => 'Устранение засоров механическим способом в {:prepositional}',
                'title' => 'Устранение засоров механическим способом в {:prepositional}. Низкая цена. Профессионально. Быстро.',
                'description' => 'Устранение засоров механическим способом в {:prepositional} - Доступные цены!
                                   Приезд сантехника через 45 минут после обращения. Звоните и узнайте стоимость.',
                'keywords' => 'сантехника, засор, унитаза, механический способ, {:name}',
                'default_template' => 'templates.services.plumber.removing_blockages.8-mechanic_method_clearing',
                'main_service' => false,
                'on_city_list' => false,
                'section' => false,
                'default_price' => '700',
                'sort' => 67
            ],
        ]);
    }
}
